SAMPLE_CONFIRMATION = "SAMPLE_CONFIRMATION"
FABRIC_BOOKING = "FABRIC_BOOKING"
TRIM_BOOKING = "TRIM_BOOKING"
CUTTING = "CUTTING"
SEWING = "SEWING"
WASHING_OR_FINISHING = "WASHING_OR_FINISHING"
INLINE_QC = "INLINE_QC"
FINAL_QC = "FINAL_QC"
PACKING = "PACKING"
LOGISTICS_HANDOVER = "LOGISTICS_HANDOVER"
SHIPMENT = "SHIPMENT"
BUYER_SIGN_OFF = "BUYER_SIGN_OFF"

ORDERED_MILESTONES = [
    SAMPLE_CONFIRMATION, FABRIC_BOOKING, TRIM_BOOKING,
    CUTTING, SEWING, WASHING_OR_FINISHING,
    INLINE_QC, FINAL_QC, PACKING,
    LOGISTICS_HANDOVER, SHIPMENT, BUYER_SIGN_OFF,
]
