STANDARD_FIELDS = [
    "product_type",
    "product_category",
    "quantity",
    "fabric_type",
    "fabric_composition",
    "fabric_weight_gsm",
    "color",
    "size_range",
    "size_breakdown",
    "pattern_or_cutting_requirement",
    "trim_requirement",
    "label_requirement",
    "washing_mark_requirement",
    "packaging_requirement",
    "qc_standard",
    "sample_requirement",
    "delivery_deadline",
    "trade_term",
    "destination",
    "payment_term",
    "compliance_requirement",
    "special_notes",
    "missing_fields",
    "clarification_questions",
]

REQUIRED_FIELDS = [
    "product_type",
    "quantity",
    "fabric_type",
    "color",
    "size_range",
    "delivery_deadline",
    "trade_term",
    "destination",
]

FIELD_DESCRIPTIONS = {
    "product_type": "Type of apparel product (e.g. T-shirt, trousers, jacket)",
    "product_category": "Product category (men/women/children/unisex)",
    "quantity": "Total order quantity in pieces",
    "fabric_type": "Main fabric type (e.g. 100% cotton, polyester blend)",
    "fabric_composition": "Exact fabric composition with percentages",
    "fabric_weight_gsm": "Fabric weight in GSM",
    "color": "Color or colorway specification",
    "size_range": "Size range required (e.g. XS-XXL, EU 38-46)",
    "size_breakdown": "Quantity breakdown by size",
    "pattern_or_cutting_requirement": "Pattern, cut or construction notes",
    "trim_requirement": "Buttons, zippers, labels, threads etc.",
    "label_requirement": "Brand label, care label, country of origin label",
    "washing_mark_requirement": "Washing and care instruction marks",
    "packaging_requirement": "Individual polybag, box, hanger, carton details",
    "qc_standard": "QC standard to be applied (e.g. AQL 2.5)",
    "sample_requirement": "Pre-production sample or photo sample required",
    "delivery_deadline": "Required delivery date (FOB/CIF/DDU as applicable)",
    "trade_term": "Trade term (FOB/CIF/EXW/DDP etc.)",
    "destination": "Destination port or address",
    "payment_term": "Payment terms (e.g. 30% deposit, 70% before shipment)",
    "compliance_requirement": "Compliance certifications (REACH, OEKO-TEX, etc.)",
    "special_notes": "Any other special requirements",
}
