BUYER = "BUYER"
INTERMEDIARY = "INTERMEDIARY"
TRADING_COMPANY = "TRADING_COMPANY"
MANUFACTURER = "MANUFACTURER"
FABRIC_SUPPLIER = "FABRIC_SUPPLIER"
TRIM_SUPPLIER = "TRIM_SUPPLIER"
PACKAGING_SUPPLIER = "PACKAGING_SUPPLIER"
LOGISTICS_PROVIDER = "LOGISTICS_PROVIDER"
FINANCE_SERVICE_PROVIDER = "FINANCE_SERVICE_PROVIDER"
QC_INSPECTOR = "QC_INSPECTOR"
PLATFORM_ADMIN = "PLATFORM_ADMIN"

ALL_ROLES = [
    BUYER, INTERMEDIARY, TRADING_COMPANY, MANUFACTURER,
    FABRIC_SUPPLIER, TRIM_SUPPLIER, PACKAGING_SUPPLIER,
    LOGISTICS_PROVIDER, FINANCE_SERVICE_PROVIDER,
    QC_INSPECTOR, PLATFORM_ADMIN,
]
